
name: Crear carpeta de nueva aplicaci贸n laboral

on:
  push:
    paths:
      - 'to_process/*.yaml'

jobs:
  crear-carpeta-aplicacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pyyaml

      - name: Procesar archivo de nueva aplicaci贸n
        run: |
          for file in to_process/*.yaml; do
            python scripts/procesar_aplicacion.py "$file"
          done

      - name: Commit y push de cambios
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Automatizaci贸n: Nueva aplicaci贸n laboral creada por workflow" || echo "Sin cambios para commitear"
          git push
