name: Crear carpeta de nueva aplicación laboral

on:
  push:
    paths:
      - 'to_process/*.yaml'
permissions:
  contents: write
  issues: write
  repository-projects: write

jobs:
  crear-carpeta-aplicacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pyyaml requests

      - name: Instalar pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Instalar LaTeX (paquetes recomendados)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-recommended texlive-xetex texlive-fonts-recommended texlive-latex-extra

      - name: Procesar archivo de nueva aplicación
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in to_process/*.yaml; do
            python aplicaciones_laborales/scripts/procesar_aplicacion.py "$file"
          done

      - name: Validar configuración de repositorio destino
        id: check_target_repo
        env:
          # Use PAT_APLICACION_LABORAL for cross-repo access to private repos, fallback to GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.PAT_APLICACION_LABORAL || secrets.GITHUB_TOKEN }}
        run: |
          TARGET_REPO="angra8410/todas-mis-aplicaciones"
          echo "Verificando si el repositorio destino existe..."
          echo ""
          
          # Check which token is being used
          if [ -n "${{ secrets.PAT_APLICACION_LABORAL }}" ]; then
            echo "🔑 Usando PAT_APLICACION_LABORAL para acceso cross-repo"
          else
            echo "⚠️  Usando GITHUB_TOKEN (puede no funcionar con repos privados)"
          fi
          echo ""

          # Check if the repository exists using GitHub API
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$TARGET_REPO")
          
          echo "📊 Código de respuesta HTTP: $HTTP_CODE"
          echo ""

          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Repositorio destino encontrado y accesible: $TARGET_REPO"
            echo "repo_exists=true" >> $GITHUB_OUTPUT
          elif [ "$HTTP_CODE" = "404" ]; then
            echo "❌ ERROR: Repositorio no encontrado (HTTP 404)"
            echo "   Repositorio: $TARGET_REPO"
            echo ""
            echo "📋 ACCIÓN REQUERIDA:"
            echo "   1. Verifica que el repositorio existe en:"
            echo "      https://github.com/$TARGET_REPO"
            echo "   2. Si es privado, configura PAT_APLICACION_LABORAL en secrets"
            echo "   3. Revisa SETUP_REQUIRED.md para instrucciones completas"
            echo ""
            echo "repo_exists=false" >> $GITHUB_OUTPUT
          elif [ "$HTTP_CODE" = "401" ] || [ "$HTTP_CODE" = "403" ]; then
            echo "❌ ERROR: Problema de autenticación/permisos (HTTP $HTTP_CODE)"
            echo "   Repositorio: $TARGET_REPO"
            echo ""
            echo "📋 ACCIÓN REQUERIDA:"
            echo "   El repositorio existe pero no es accesible con el token actual."
            echo ""
            echo "   Para repositorios PRIVADOS, debes configurar un PAT:"
            echo "   1. Crea un Personal Access Token en:"
            echo "      https://github.com/settings/tokens/new"
            echo "   2. Permisos requeridos: 'repo' (acceso completo a repos privados)"
            echo "   3. Agrega el token como secret 'PAT_APLICACION_LABORAL' en:"
            echo "      https://github.com/angra8410/aplicaciones_laborales/settings/secrets/actions"
            echo "   4. Revisa SETUP_REQUIRED.md sección 'Configurar PAT' para detalles"
            echo ""
            echo "repo_exists=false" >> $GITHUB_OUTPUT
          else
            echo "⚠️  ADVERTENCIA: Error inesperado (HTTP $HTTP_CODE)"
            echo "   Repositorio: $TARGET_REPO"
            echo ""
            echo "repo_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Copiar CV PDF a repositorio todas-mis-aplicaciones
        if: steps.check_target_repo.outputs.repo_exists == 'true'
        env:
          # Use PAT_APLICACION_LABORAL for cross-repo access to private repos, fallback to GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.PAT_APLICACION_LABORAL || secrets.GITHUB_TOKEN }}
        run: |
          echo "🔄 Iniciando copia de PDFs al repositorio todas-mis-aplicaciones"
          echo ""
          
          # Find the most recently created folder in to_process_procesados
          for folder in to_process_procesados/*/; do
            if [ -d "$folder" ]; then
              folder_name=$(basename "$folder")
              # Skip if it's just the YAML file
              if [[ "$folder_name" != *.yaml ]]; then
                echo "📁 Procesando copia de PDF para: $folder_name"
                python aplicaciones_laborales/scripts/copy_pdf_to_documents_repo.py "$folder_name" || echo "⚠️  Advertencia: No se pudo copiar PDF para $folder_name"
                echo ""
              fi
            fi
          done
          
          echo "✅ Proceso de copia de PDFs completado"

      - name: Commit y push de cambios
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Automatización: Nueva aplicación laboral creada por workflow" || echo "Sin cambios para commitear"
          git push
