name: Crear carpeta de nueva aplicaci贸n laboral

on:
  push:
    paths:
      - 'to_process/*.yaml'
permissions:
  contents: write

jobs:
  crear-carpeta-aplicacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pyyaml

      - name: Instalar pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Instalar LaTeX (paquetes recomendados)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-recommended texlive-xetex texlive-fonts-recommended texlive-latex-extra

      - name: Procesar archivo de nueva aplicaci贸n
        run: |
          for file in to_process/*.yaml; do
            python aplicaciones_laborales/scripts/procesar_aplicacion.py "$file"
          done

      - name: Convertir hojas de vida Markdown a PDF
        run: |
          find to_process_procesados -name "hoja_de_vida_adecuada.md" | while read mdfile; do
            empresa=$(basename $(dirname "$mdfile"))
            pdfdir=$(dirname "$mdfile")
            nombre_empresa=$(echo "$empresa" | awk -F_ '{print $(NF-1)}')
            pdffile="$pdfdir/ANTONIO_GUTIERREZ_RESUME_${nombre_empresa}.pdf"
            pandoc "$mdfile" -o "$pdffile"
          done

      - name: Commit y push de cambios
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Automatizaci贸n: Nueva aplicaci贸n laboral creada por workflow" || echo "Sin cambios para commitear"
          git push
